# Generated by Django 2.1.7 on 2019-04-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='wallpaper',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection'),
        ),
    ]
